### PR TITLE
object-manipulation-3 - Jared Jenvey

### PR DESCRIPTION
**Pull request by JCJenvey**
object-manipulation-3

### CODE REVIEW

**Review by scrumptiousdev — CHANGES_REQUESTED** [review]
Nice how it tracks the previous score when you keep running `runGame(players, 2)`. However, is it possible to know the winner for each round instead of the overall score winner?

**Comment by JCJenvey** [comment]
object-manipulation-3(2)

**Comment by JCJenvey** [comment]
The fact that the same player kept winning is an honest coincidence that I didn't notice. Other tests with te old version had differing players win.

**Review by scrumptiousdev — APPROVED** [review]
Approved!

**Pull request merged**
